apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-with-httpd
  labels:
    system: joker
    environment:  sqa
spec:
  replicas: 5
  minReadySeconds:  30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector: 
    matchLabels:
      app:  frontend
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      containers:
        - name: httpd-with-deployment
          image: httpd:alpine
          env:  
            - name:  DATABASE_IP
              value:  pakito_server
          ports:
            - containerPort: 80