apiVersion: v1
kind: Pod
metadata:
  name: first-pod-in-namespace
  namespace:  first-custom-namespace
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: DATABASE_IP
          value:  80.52.32.45
      ports:
        - containerPort: 80