apiVersion: v1
kind: Pod
metadata:
  name: pod-with-1-container-and-env
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: DATABASE_IP
          value:  80.52.32.45
      ports:
        - containerPort: 80