apiVersion: v1
kind: Pod
metadata:
  name: single-pod-for-replicaset
  labels: 
    app: frontend 
spec:
  containers:
    - name: pakito-server
      image: tomcat:apline
      ports:
        - containerPort: 8080